version: "3"
services:

  app: tsip_ruby
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    ports: # Проброс портов
      - "3000:8000"
    volumes:
      - ".:/app"
      - "/tmp:/tmp"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ['1234']
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  volumes:
    pgdata: